# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for linux kernel module support
#

obj-$(CONFIG_MODULES) += main.o
obj-$(CONFIG_MODULE_SIG) += signing.o
obj-$(CONFIG_MODULE_SIG_FORMAT) += signature.o
obj-$(CONFIG_LIVEPATCH) += livepatch.o
obj-$(CONFIG_MODULES_TREE_LOOKUP) += tree_lookup.o
